#version: '3.7'

services:
  postgresql-llms:
    image: postgres:latest
    container_name: postgresql-llms
    restart: unless-stopped
    hostname: postgresql-server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  redis_server:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDISPwd}
      - REDIS_PORT_NUMBER=${REDISPort}
    volumes:
      - redis-data:/bitnami
    ports:
      - "6379:6379"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 9000:3000
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  postgresql-data:
  redis-data:
  grafana-data:
