apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-metrics-chart.api.fullname" . }}
  labels:
    app: {{ include "llm-metrics-chart.name" . }}
    service: api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "llm-metrics-chart.name" . }}
      service: api
  template:
    metadata:
      labels:
        app: {{ include "llm-metrics-chart.name" . }}
        service: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
          env:
            - name: DB_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: llm-metrics-db-secret
                  key: connectionString
            - name: DB_HOST
              value: {{ .Values.postgres.host }}
            - name: DB_PORT
              value: {{ .Values.postgres.port }}
            - name: DB_USER
              value: {{ .Values.postgres.user }}
            - name: DB_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: DB_DB
              value: {{ .Values.postgres.database }}
            - name: REDIS_ADDR
              value: "{{ .Values.redis.host }}:{{ .Values.redis.port }}"

