apiVersion: v1
kind: Secret
metadata:
  name: llm-metrics-db-secret
type: Opaque
data:
  connectionString: {{ printf "postgres://%s:%s@postgres:5433/%s?sslmode=disable" .Values.postgresql.username .Values.postgresql.password .Values.postgresql.database | b64enc }}

